escola/core/urls.py
from django.contrib import admin
from django.urls import path

from core.views import MainView,ProfessorListView,ProfessorModalCreateView
from core.views import ProfessorTableListView,ProfessorDeleteView,ProfessorModalUpdateView

urlpatterns = [
    path('', MainView.as_view(),name='main-page'),
    path('professor/', ProfessorListView.as_view(),name='professor-list'),
    path('professor/create/', ProfessorModalCreateView.as_view(),name='professor-create'),
    path('professor/list/',ProfessorTableListView.as_view(),name='professor-table-list'),
    path('professor/<int:pk>/edit', ProfessorModalUpdateView.as_view(),name='professor-edit'),
    path('professor/<int:pk>/delete', ProfessorDeleteView.as_view(),name='professor-delete'),
]

escola/escola/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include("core.urls"))
]

escola/core/models.py
from django.db import models

class Professor(models.Model):
  GRADUADO = 'G'
  ESPECIALISTA = 'E'
  MESTRE = 'M'
  DOUTOR = 'D'

  TITULACAO_CHOICES = [
    (GRADUADO, 'Graduado'),
    (ESPECIALISTA, 'Especialista'),
    (MESTRE, 'Mestre'),
    (DOUTOR, 'Doutor'),
  ]
  
  matricula = models.AutoField(primary_key=True)
  nome = models.CharField(max_length=50)
  endereco = models.CharField(max_length=200)
  telefone = models.CharField(max_length=11)
  titulacao = models.CharField(max_length=1, choices= TITULACAO_CHOICES)

  @staticmethod
  def get_choice(name):
    for choice in Professor.TITULACAO_CHOICES:
      code, choice_name = choice
      if choice_name == name:
        return code
    return ""

escola/core/forms.py
from django import forms

from core.models import Professor

class ProfessorForm(forms.ModelForm):
  matricula = forms.IntegerField(widget = forms.HiddenInput(),required=False)
  class Meta:
    model = Professor
    fields = "__all__"

escola/core/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView,ListView,CreateView,DeleteView,UpdateView
from django.views.generic.edit import DeletionMixin,SingleObjectMixin,View
from django.http.response import HttpResponse
from http import HTTPStatus

from django.db.models import Q

from core.forms import ProfessorForm
from core.models import Professor


class DeleteViewWithoutRedirect(SingleObjectMixin,DeletionMixin,View):
  """
  Implemensts custom delete vie
  """
  def delete(self, request, *args, **kwargs):
    super().delete(request,args,kwargs)
    
    return HttpResponse(status= HTTPStatus.NO_CONTENT)

  def get_success_url(self):
    return "/"

class MainView (TemplateView):
  template_name= "main.html" 

class ProfessorListView (TemplateView):
  template_name= "professor/list.html"

class ProfessorModalCreateView (CreateView):
  template_name = "professor/modal/add-professor.html"
  model = Professor
  form_class = ProfessorForm
  success_url = reverse_lazy('professor-list')

class ProfessorModalUpdateView (UpdateView):
  template_name= "professor/modal/edit-professor.html"
  form_class = ProfessorForm
  success_url = reverse_lazy('professor-list')
  queryset = Professor.objects.all()

class ProfessorDeleteView(DeleteViewWithoutRedirect):
  model = Professor

class ProfessorTableListView(ListView):
  model = Professor
  template_name= "professor/table-list.html"

  def get_queryset(self):
    search = self.request.GET.get('search')
    if search : 
      filtro = None
      try:
        number_search = int(search)
        filtro = Q(matricula__exact=number_search)
      except:
        pass
      
      if not filtro:
        filtro = Q(nome__icontains=search)
      else:
        filtro |= Q(nome__icontains=search)

      code_titulacao = Professor.get_choice(search)

      filtro |= Q(endereco__icontains=search) | Q(telefone__icontains=search) | Q(titulacao = code_titulacao)

      return Professor.objects.filter(filtro)
    
    return Professor.objects.all()

escola/core/templates/main.html
{% extends 'template.html' %} 
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock styles %}
{% block content %}
  <div class="main-card card mb-3">
    <div class="card-header bg-purple text-white"><h3>Sistema De Cadastro Escolar</h3></div>
    <div class="card-body">
      <h5 class="card-title text-purple font-weight-bolder">Selecione abaixo o que você deseja cadastrar </h5>
      <ul class="list-group list-group-flush register">
        <li class="list-group-item">
          <div class="d-flex justify-content-between align-items-center ">
            <span class="font-weight-bolder w-100" onclick="go('{% url 'professor-list' %}')" > 
              <i class="fas fa-chalkboard-teacher mr-1"></i>
              Professor
            </span>
            <span class="actions">
              <a class="action" href="{% url 'professor-list' %}">
                <i class="fas fa-clipboard-list"></i>
              </a>
              <a class="action" onclick="show('{% url 'professor-create' %}')">
                <i class="fas fa-plus"></i>
              </a>
            </span>
          </div>
        </li>
      </ul>
    </div>
  </div>
  {% include 'professor/modal/base-professor.html' %}
{% endblock content %}

escola/core/templates/professor/list.html
{% extends 'template.html' %} 
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/professor/list.css' %}">
{% endblock styles %}
{% block content %}
  <div class="list-card card w-100">
    <div class="card-header bg-purple text-white">
      <div class="row">
        <div class="col-1">
          <a class="text-white scale" href="{% url 'main-page' %}">
            <i class="fas fa-arrow-left fa-2x mr-2"></i>
          </a>
        </div>
        <div class="col-10">
          <h3>
            Listagem de Professores
          </h3>
        </div>
      </div>
    </div>
    <div class="card-body d-flex flex-column">
      <div class="d-flex justify-content-between align-items-center row">
        <div class="col-sm-12 col-md-6 col-lg-4 mb-2"> 
          <form id="search">
            <div class="input-group">
              <input type="text" class="form-control purple" name="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-purple" type="submit" id="button-addon2">
                  <i class="fas fa-search"></i>
                </span>
              </div>
            </div>
          <form>
        </div>
        <div class="col-sm-12 col-md-5 col-lg-3 d-flex justify-content-end mb-2"> 
            <button class="btn btn-purple btn-md" type="button" id="button-addon2" onclick="show('{% url 'professor-create' %}')">
              <i class="fas fa-plus mr-1"></i> Adicionar Professor
            </span>
        </div>
      </div>
      <div class="table-responsive-sm fill-content-flex tableFixHead">
        <table id="table-professores" class="table table-striped table-borderless">
          <thead class="text-purple font-weigth-bolder text-center bg-white">
            <tr>
              <th scope="col">#Matrícula</th>
              <th scope="col">Nome</th>
              <th scope="col">Endereço</th>
              <th scope="col">Telefone</th>
              <th scope="col">Titulação</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>
          <tbody class="text-center" >
            <tr>
              <td scope="row" colspan="6"> Não achamos nenhum cadastro de professor! </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% include 'professor/modal/base-professor.html' %}
  
{% endblock content %}
{% block script %}
<script>
  const professoresUrl = "{% url 'professor-table-list' %}";

  function getProfessores(search=""){
    $.get(`${professoresUrl}?search=${search}`)
    .done(function(response) {
      if(response && !  response.isEmpty()){
        $('#table-professores').find("tbody").html(response);
      }else{
        $('#table-professores').find("tbody").html(`
          <tr>
            <td scope="row" colspan="6"> Não achamos nenhum cadastro de professor! </td>
          </tr>`
        )
      }
    });
  }
  $(function(){
    getProfessores();
  })

  function deleteProfessor(url){
    $.confirm({
      icon: 'fa fa-warning',
      title: 'font-awesome',
      type: 'purple',
      typeAnimated: true,
      title: 'Confirmação de Deleção',
      content: 'Você tem certeza que deseja deletar o professor ?',
      buttons: {
        confirm: {
          text: "Sim",
          btnClass: 'btn-purple',
          action : function(){
            $.ajax({
              url: url,
              type: 'DELETE'
            }).then(()=>{
              go(location.href)
            });
          }
        },
        cancel: {
          text:"Não",
          action: function(){
            
          }
        }
      }
    });
  }

  $("#search").on("submit",(event)=>{
    event.preventDefault();
    const search = $(event.target).find("input").val();
    console.log(search);

    getProfessores(search);
  });

</script>  
{% endblock script %}

escola/core/templates/professor/modal/add-professor.html
{% url 'professor-create' as create_url %}
{% include 'professor/modal/modal-content.html' with title="Cadastrar Professor" url=create_url %}

escola/core/templates/professor/modal/base-professor.html
<div class="modal fade" id="professor-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  </div>
</div>

escola/core/templates/professor/modal/edit-professor.html
{% url 'professor-edit' form.matricula.value as edit_url %}
{% include 'professor/modal/modal-content.html' with title="Editar Professor" url=edit_url %}

escola/core/templates/professor/modal/modal-content.html
{% load filters %}
<div class="modal-content">
  <div class="modal-header bg-purple text-white">
    <h5 class="modal-title">{{title}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <i class="fas fa-times text-white"></i>
    </button>
  </div>
  <div class="modal-body">
    <form id="professor-form" action="{{ url }}">
      {% csrf_token %}
      {% if form.matricula.value %}
        <div class="form-group">
          <label for="{{ form.nome.id_for_label }}">Matricula</label>
          <div class="output">
            {{ form.matricula }}
            {{form.matricula.value}}
          </div>
        </div>
      {% endif %}
      <div class="form-group">
        <label for="{{ form.nome.id_for_label }}">Nome</label>
        {{form.nome | class:'form-control purple text-capitalize' }}
        <small id="emailHelp" class="form-text text-muted text-danger">
          {{form.nome.errors }}
        </small>  
      </div>
      <div class="form-group purple">
        <label for="{{ form.titulacao.id_for_label }}">Titulação</label>
        {{form.titulacao | class:'select2 custom-select' }}
        <small id="emailHelp" class="form-text text-muted text-danger">
          {{form.titulacao.errors }}
        </small>  
      </div>
      <div class="form-group">
        <label for="{{ form.endereco.id_for_label }}">Endereço</label>
        {{form.endereco | class:'form-control purple text-capitalize' }}
        <small id="emailHelp" class="form-text text-muted text-danger">
          {{form.endereco.errors }}
        </small>  
      </div>
      <div class="form-group">
        <label for="{{ form.telefone.id_for_label }}">Telefone</label>
        {{form.telefone | class:'form-control purple phone' }}
        <small id="emailHelp" class="form-text text-muted text-danger">
          {{form.telefone.errors }}
        </small>  
      </div>
      <div class="d-flex justify-content-end">
        <button type="button" class="btn btn-outline-secondary mr-2" data-dismiss="modal"><i class="fas fa-arrow-left"></i> Cancelar</button>
        <button type="submit" class="btn btn-purple"><i class="fas fa-check"></i> Salvar</button>
      </div>
    </form>
  </div>
</div>
<script>
   
  new Form('professor-form')
  .onSuccess(()=>{
    hide();
    go("{% url 'professor-list' %}");
  }).onFail(()=>{
    alert(error);
  }).addSanitize("telefone",(telefone)=> (telefone.replace(/\D/g, '')))
  .addSanitize("nome",(nome)=> (nome.toLowerCase()))
  .addSanitize("endereco",(endereco)=> (endereco.toLowerCase()))
  .init();

  $(".select2").find("option[value='']").text("Selecione uma opção");
  $(".select2").attr("style","width: 100%;").select2({
    minimumResultsForSearch: Infinity
  });

  var PhoneMaskBehavior = function (val) {
    return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
  };

  var options =  {
    onKeyPress: function(phone, e, field, options) {
      field.mask(PhoneMaskBehavior.apply({}, arguments), options);
    },
    placeholder: '(00) 0 0000-0000'
  };

  $('.phone').mask(PhoneMaskBehavior, options);

</script>

escola/core/templates/professor/table-list.html
{% load filters %}
{% for professor in object_list %}
  <tr>
    <td scope="row">{{professor.matricula}}</td>
    <td scope="row">{{professor.nome}}</td>
    <td scope="row">{{professor.endereco}}</td>
    <td scope="row">{{professor.telefone |mask:"phone"}}</td>
    <td scope="row">{{professor.get_titulacao_display}}</td>
    <td scope="row" class="d-flex justify-content-center">
      <span class="actions">
        <a class="action" title="Editar" onclick="show('{% url 'professor-edit' professor.matricula %}')">
          <i class="fas fa-pen"></i>
        </a>
        <a class="action" title="Excluir" onclick="deleteProfessor('{% url 'professor-delete' professor.matricula %}')">
          <i class="fas fa-trash-alt"></i>
        </a>
      </span>
    </td>
  </tr>
{% endfor %}

escola/core/templates/template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Escola</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'lib/boostrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'lib/fontawesome/css/all.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'lib/select2/select2.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'lib/toastr/toastr.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'lib/jquery-confirm/jquery-confirm.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    {% block styles %}{% endblock styles %}
  </head>
  <body>
    <main class="container-fluid h-100">
      <div class="main-content">
        {% block content %}{% endblock content %}
      </div>
    </main>
    {% csrf_token %}
    <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/popper/popper.min.js' %}"></script>
    <script src="{% static 'lib/select2/select2.min.js' %}"></script>
    <script src="{% static 'lib/toastr/toastr.min.js' %}"></script>
    <script src="{% static 'lib/jquery-confirm/jquery-confirm.min.js' %}"></script>
    <script src="{% static 'lib/jquery-mask/jquery-mask.min.js' %}"></script>
    <script src="{% static 'lib/boostrap/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/form.js' %}"></script>
    <script src="{% static 'js/professor/modal.js' %}"></script>

    {% block script %}{% endblock script %}
  </body>
</html>